### ISSUE TITLE
Where can I download SDK 10.22000.1

### ISSUE THREAD

**Issue by fluffydolphin** [StephanvanSchaik/windows-kernel-rs#8]
The windows SDK version 10.22000.1 is not in the windows SDK archive page, where can I download it from. anything is greatly appreciated thx.

**Comment by StephanvanSchaik** [comment]
10.22000.1 was a preview of the Windows 11 SDK at the time. Are you running into any issues with a newer version of the SDK?

I should probably update any references once I get some time to check this on a Microsoft Windows machine again.

**Comment by fluffydolphin** [comment]
yea sorry I'm really new to kernel drivers in windows and I thought that there would be some issue if i used a newer version, but it all works fine thx.

**Comment by Jhynjhiruu** [comment]
I'm trying to use this with a Windows 10 machine with the latest version of the SDK and it's very unhappy with me. Some very basic diagnostics point to `_MSC_VER` being undefined, leading to the DDK headers rejecting bindgen. That means that the very basic hello world example works fine, but everything beyond that point fails to compile with a horrible wall of impenetrable error messages.
